[context.production.environment]
    REACT_APP_ENDPOINT="https://story-squad.herokuapp.com"
    GENERATE_SOURCEMAP="false"


[context.deploy-preview.environment]
    REACT_APP_ENDPOINT="https://story-squad.herokuapp.com"
    GENERATE_SOURCEMAP="false"


[context."webpack".environment]
    REACT_APP_ENDPOINT="https://core-webpack-31236dhik9frjxddz.herokuapp.com"


[context."multi-page-submissions".environment]
    REACT_APP_ENDPOINT="https://core-multi-page-submiss-kkrxn7.herokuapp.com"