[context.production.environment]
    REACT_APP_ENDPOINT="https://story-squad.herokuapp.com"
    GENERATE_SOURCEMAP="false"


[context.deploy-preview.environment]
    REACT_APP_ENDPOINT="https://story-squad.herokuapp.com"
    GENERATE_SOURCEMAP="false"


[context."moderator".environment]
    REACT_APP_ENDPOINT="https://core-moderator-l07ugg7dkpwb22w.herokuapp.com"