[context.production.environment]
    REACT_APP_ENDPOINT="https://story-squad.herokuapp.com"
    GENERATE_SOURCEMAP="false"


[context.deploy-preview.environment]
    REACT_APP_ENDPOINT="https://story-squad.herokuapp.com"
    GENERATE_SOURCEMAP="false"


[context."nestjs".environment]
    REACT_APP_ENDPOINT="https://core-nestjs-czbjbbyn93dl9y5yh4.herokuapp.com"


