[context.production.environment]
    REACT_APP_ENDPOINT="https://story-squad.herokuapp.com"


[context."create-account".environment]
    REACT_APP_ENDPOINT="https://staging-create-account-46n6xrs.herokuapp.com"


[context."child-account-management".environment]
    REACT_APP_ENDPOINT="https://staging-child-account-m-8xrbt8.herokuapp.com"