[context.production.environment]
    REACT_APP_ENDPOINT="https://story-squad.herokuapp.com"


[context.deploy-preview.environment]
    REACT_APP_ENDPOINT="https://story-squad.herokuapp.com"


[context."polish".environment]
    REACT_APP_ENDPOINT="https://core-polish-ggzspu1w8t31chhldk.herokuapp.com"