import { makeStyles, Theme, createStyles } from '@material-ui/core/styles';

import cityscape from '../child-dashboard/kid-progress/icons/cityscape.png';
import splode from './img/splode.png';

export const useStyles = makeStyles((theme: Theme) =>
    createStyles({
        modal: {
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
        },
        paper: {
            backgroundColor: theme.palette.background.paper,
            border: '2px solid #000',
            boxShadow: theme.shadows[5],
            padding: theme.spacing(2, 4, 3),
        },
        root: {
            fontFamily: 'nunito',
            display: 'flex',
            flexDirection: 'column',
            maxHeight: '510%',
        },
        gridRow1: {
            height: '274px',
            backgroundColor: '#EB7D5B',
            paddingTop: '32px',
            padding: '30px',
            borderTop: '7px solid #000000',
            borderLeft: '14px solid #000000',
        },
        gridRow2: {
            height: '274px',
            backgroundColor: '#EB7D5B',
            paddingTop: '32px',
            padding: '30px',
            borderTop: '7px solid #000000',
            borderRight: '14px solid #000000',
        },
        gridRow3: {
            height: '274px',
            backgroundColor: '#FED23F',
            paddingTop: '32px',
            padding: '30px',
            borderTop: '7px solid #000000',
            borderLeft: '14px solid #000000',
        },
        gridRow4: {
            height: '274px',
            backgroundColor: '#FED23F',
            paddingTop: '32px',
            padding: '30px',
            borderTop: '7px solid #000000',
            borderRight: '14px solid #000000',
        },
        gridInput1: {
            backgroundColor: '#EB7D5B',
            padding: '53px ',
            borderLeft: '14px solid #000000',
            borderBottom: '5px solid #000000',
        },
        gridInput2: {
            backgroundColor: '#EB7D5B',
            padding: '53px ',
            borderRight: '14px solid #000000',
            borderBottom: '5px solid #000000',
        },
        gridInput3: {
            backgroundColor: '#FED23F',
            padding: '50px ',
            borderLeft: '14px solid #000000',
            borderBottom: '14px solid #000000',
            marginBottom: '60px',
        },
        gridInput4: {
            backgroundColor: '#FED23F',
            padding: '20px ',
            borderRight: '14px solid #000000',
            borderBottom: '14px solid #000000',
            marginBottom: '60px',
        },
        avatarMargin: {
            fontFamily: 'nunito',
            fontSize: '18px',
            fontWeight: 'bold',
            backgroundColor: '#B5D33D',
            padding: '26px 6px 11px 6px',
            borderLeft: '14px solid #000000',
            borderTop: '7px solid #000000',
        },
        avatarMargin2: {
            fontFamily: 'nunito',
            fontSize: '18px',
            fontWeight: 'bold',
            backgroundColor: '#B5D33D',
            padding: '25px 9px 19px 9px',
            borderLeft: '14px solid #000000',
        },
        avatarMargin3: {
            backgroundColor: '#B5D33D',
            padding: '20px 20px 20px 20px',
            borderLeft: '14px solid #000000',
            borderBottom: '14px solid #000000',
            marginBottom: '60px',
        },
        avatarMargin4: {
            backgroundColor: '#B5D33D',
            padding: '61px 55px 50px 55px',
            borderLeft: '14px solid #000000',
        },
        orangeButton: {
            'backgroundColor': '#FF6B35',
            'fontSize': '24px',
            'fontWeight': 'bold',
            'borderRadius': '10px',
            'color': 'white',
            'width': '200px',
            'border': '3px solid #292929',
            'textTransform': 'capitalize',
            'fontFamily': 'nunito',
            '&:hover': {
                backgroundColor: '#FF6B35',
            },
        },
        pointInput: {
            fontFamily: 'Bangers',
            fontSize: '48px',
            fontWeight: 'bold',
        },
        imagePreview: {
            width: '250px',
            height: '125px',
            borderRadius: '14px',
        },
        containerStyling: {
            fontFamily: 'nunito',
        },
        h2Styling: {
            'fontFamily': 'Bangers',
            'color': '#FFFFFF',
            'fontSize': '86px',
            'fontWeight': 'bold',
            '-webkit-text-stroke-width': '1px',
            '-webkit-text-stroke-color': '#000000',
        },
        h3Styling: {
            'fontFamily': 'Bangers',
            'color': '#FFFFFF',
            'fontSize': '48px',
            'fontWeight': 'bold',
            '-webkit-text-stroke-width': '1px',
            '-webkit-text-stroke-color': '#000000',
            'marginTop': '60px',
        },
        avatarStyling: {
            marginTop: '25px',
            width: '215px',
            height: '180px',
            backgroundImage: `url(${splode})`,
            backgroundRepeat: 'no-repeat',
            backgroundSize: '101% 103%',
        },
        red: {
            color: 'red',
        },
        appBar: {
            height: '200px',
            width: '100%',
            backgroundColor: '#6CEAE6',
            backgroundImage: `url(${cityscape})`,
            backgroundRepeat: 'no-repeat',
            border: '7px solid #000000',
            backgroundSize: '101% 103%',
            display: 'flex',
            justifyContent: 'center',
        },
        username1: {
            'position': 'absolute',
            'top': '395px',
            'fontFamily': 'Bangers',
            'color': '#FFFFFF',
            'fontSize': '48px',
            'fontWeight': 'bold',
            '-webkit-text-stroke-width': '1px',
            '-webkit-text-stroke-color': '#000000',
        },
        username2: {
            'position': 'absolute',
            'top': '768px',
            'fontFamily': 'Bangers',
            'color': '#FFFFFF',
            'fontSize': '48px',
            'fontWeight': 'bold',
            '-webkit-text-stroke-width': '1px',
            '-webkit-text-stroke-color': '#000000',
        },
    })
);
